from dishka import Provider, Scope, provide, provide_all

from app.product.position.cmd import (
    AddPositionItem,
    AddPositionItems,
    AddPositionMedia,
    ArchiveAllPositionItems,
    ArchiveAllPositionsInCategory,
    ArchivePosition,
    ArchivePositionItem,
    ChangePositionDescriptionDefaultLang,
    ChangePositionNameDefaultLang,
    ChangePositionPriceBaseCurrency,
    ConvertPositionPriceToOthers,
    CreatePosition,
    DeleteAllPositionItems,
    DeleteAllPositionsInCategory,
    DeletePosition,
    DeletePositionItem,
    RecoverPosition,
    RecoverPositionItem,
    RemovePositionDescription,
    RemovePositionMedia,
    RemovePositionName,
    ReplacePositionItem,
    ReplacePositionMedia,
    SetPositionDescription,
    SetPositionName,
    SetPositionPrice,
    TranslatePositionDescriptionToOthers,
    TranslatePositionNameToOthers,
)
from app.product.position.query import (
    GetPosition,
    GetPositionItem,
    GetPositionWithItemsAmount,
    ListPositionItems,
    ListPositionsByCategory,
    ListPositionsShortByCategory,
    ListPositionsWithItemsAmountByCategory,
)


class PositionHandlersProvider(Provider):
    scope = Scope.REQUEST

    commands = provide_all(
        provide(CreatePosition),
        provide(AddPositionItems),
        provide(ChangePositionDescriptionDefaultLang),
        provide(AddPositionMedia),
        provide(ChangePositionNameDefaultLang),
        provide(RecoverPosition),
        provide(ArchivePosition),
        provide(RemovePositionDescription),
        provide(RemovePositionMedia),
        provide(RemovePositionName),
        provide(ReplacePositionMedia),
        provide(SetPositionDescription),
        provide(SetPositionName),
        provide(SetPositionPrice),
        provide(TranslatePositionNameToOthers),
        provide(TranslatePositionDescriptionToOthers),
        provide(ConvertPositionPriceToOthers),
        provide(ReplacePositionItem),
        provide(AddPositionItem),
        provide(ArchivePositionItem),
        provide(ChangePositionPriceBaseCurrency),
        provide(DeletePosition),
        provide(DeletePositionItem),
        provide(DeleteAllPositionsInCategory),
        provide(DeleteAllPositionItems),
        provide(ArchiveAllPositionsInCategory),
        provide(RecoverPositionItem),
        provide(ArchiveAllPositionItems),
    )

    queries = provide_all(
        provide(ListPositionsByCategory),
        provide(GetPosition),
        provide(GetPositionWithItemsAmount),
        provide(ListPositionsShortByCategory),
        provide(ListPositionItems),
        provide(GetPositionItem),
        provide(ListPositionsWithItemsAmountByCategory),
    )
