from domain.common.exception import DomainError


class ItemError(DomainError): ...


class ItemSellForbidden(ItemError): ...


class ItemArchived(ItemError): ...


class ItemContentReplaceForbidden(ItemError): ...


class ItemArchivationForbidden(ItemError): ...


class ItemReservationForbidden(ItemError): ...


class ItemReleaseForbidden(ItemError): ...


class ItemDeletionForbidden(ItemError): ...
