class GeneralBotSettingsError(Exception): ...


class GeneralBotSettingsPermissionDenied(GeneralBotSettingsError): ...


class GeneralSettingsNotCreated(GeneralBotSettingsError): ...


class CannotExcludeTechWorkForUsers(GeneralBotSettingsError): ...
