"""empty message

Revision ID: c3438030bf29
Revises:
Create Date: 2026-04-15 13:33:05.070699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

from infra.framework.sql_alchemy.table.custom_type import (
    LocalizedTextType,
    FileKeyType,
    CouponValidityType,
    DiscountStrategyType,
    PaymentExternalIdType,
    ExchangeRateType,
    PositionSnapshotType,
    WarehouseStrategyType,
    PositionPriceType,
    ItemContentType,
    ItemSnapshotType,
)

# revision identifiers, used by Alembic.
revision: str = "c3438030bf29"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PaymentCommissionRule",
        sa.Column(
            "payment_method",
            sa.Enum("CRYPTO_PAY", name="paymentmethod"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("SHOP", "CUSTOMER", name="commissiontype"),
            nullable=False,
        ),
        sa.Column(
            "coefficient", sa.Numeric(precision=4, scale=3), nullable=True
        ),
        sa.PrimaryKeyConstraint(
            "payment_method", name=op.f("pk_PaymentCommissionRule")
        ),
    )
    op.create_table(
        "ReferralPolicy",
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column(
            "coefficient", sa.Numeric(precision=4, scale=3), nullable=False
        ),
        sa.PrimaryKeyConstraint(
            "current_version", name=op.f("pk_ReferralPolicy")
        ),
    )
    op.create_table(
        "User",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("referrer_id", sa.UUID(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", "SUPER_ADMIN", name="userrole"),
            nullable=False,
        ),
        sa.Column("reg_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["referrer_id"], ["User.id"], name=op.f("fk_User_referrer_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_User")),
    )
    op.create_table(
        "Category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column(
            "name", LocalizedTextType(astext_type=Text()), nullable=False
        ),
        sa.Column(
            "description", LocalizedTextType(astext_type=Text()), nullable=True
        ),
        sa.Column("media", FileKeyType(astext_type=Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "ARCHIVED", name="categorystatus"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["User.id"],
            name=op.f("fk_Category_creator_id_User"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Category")),
    )
    op.create_index(
        "uq_Category_name_values_en",
        "Category",
        [sa.literal_column("(name->'values'->>'en')")],
        unique=True,
        postgresql_where=sa.text("(name->'values'->>'en') IS NOT NULL"),
    )
    op.create_index(
        "uq_Category_name_values_ru",
        "Category",
        [sa.literal_column("(name->'values'->>'ru')")],
        unique=True,
        postgresql_where=sa.text("(name->'values'->>'ru') IS NOT NULL"),
    )
    op.create_table(
        "Coupon",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column(
            "discount",
            DiscountStrategyType(astext_type=Text()),
            nullable=False,
        ),
        sa.Column(
            "valid_from", CouponValidityType(timezone=True), nullable=False
        ),
        sa.Column(
            "valid_until", CouponValidityType(timezone=True), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["User.id"], name=op.f("fk_Coupon_creator_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Coupon")),
        sa.UniqueConstraint("code", name=op.f("uq_Coupon_code")),
    )
    op.create_table(
        "Payment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("purpose_reference_id", sa.UUID(), nullable=False),
        sa.Column(
            "purpose_type",
            sa.Enum(
                "WALLET_TOP_UP", "ORDER_PAYMENT", name="paymentpurposetype"
            ),
            nullable=False,
        ),
        sa.Column(
            "original_amount_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=False,
        ),
        sa.Column(
            "original_amount_currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=False,
        ),
        sa.Column(
            "to_pay_amount", sa.Numeric(precision=19, scale=4), nullable=False
        ),
        sa.Column(
            "commission_type",
            sa.Enum("SHOP", "CUSTOMER", name="commissiontype"),
            nullable=False,
        ),
        sa.Column(
            "commission_coefficient",
            sa.Numeric(precision=4, scale=3),
            nullable=True,
        ),
        sa.Column(
            "commission_amount",
            sa.Numeric(precision=19, scale=4),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum("CRYPTO_PAY", name="paymentmethod"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PENDING",
                "CONFIRMED",
                "FAILED",
                "CANCELLED",
                name="paymentstatus",
            ),
            nullable=False,
        ),
        sa.Column("external_id", PaymentExternalIdType(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["User.id"],
            name=op.f("fk_Payment_creator_id_User"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Payment")),
    )
    op.create_table(
        "ReferralAward",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("referrer_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "PENDING", name="referralawardstatus"),
            nullable=False,
        ),
        sa.Column("source_reference_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("ORDER", name="referralawardsourcetype"),
            nullable=False,
        ),
        sa.Column(
            "source_amount", sa.Numeric(precision=19, scale=4), nullable=False
        ),
        sa.Column(
            "source_currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=False,
        ),
        sa.Column(
            "coefficient_snapshot",
            sa.Numeric(precision=4, scale=3),
            nullable=False,
        ),
        sa.Column(
            "award_amount", sa.Numeric(precision=19, scale=4), nullable=True
        ),
        sa.Column(
            "award_currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=True,
        ),
        sa.Column(
            "exchange_rate_snapshot",
            ExchangeRateType(astext_type=Text()),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["User.id"],
            name=op.f("fk_ReferralAward_referrer_id_User"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ReferralAward")),
    )
    op.create_index(
        op.f("ix_ReferralAward_referrer_id"),
        "ReferralAward",
        ["referrer_id"],
        unique=False,
    )
    op.create_table(
        "ReferrerProfile",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "award_currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=False,
        ),
        sa.Column("send_notifications", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
            name=op.f("fk_ReferrerProfile_user_id_User"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_ReferrerProfile")),
    )
    op.create_table(
        "TelegramContext",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tg_username", sa.String(length=64), nullable=True),
        sa.Column("tg_first_name", sa.String(length=64), nullable=False),
        sa.Column("lang", sa.Enum("RU", "EN", name="language"), nullable=True),
        sa.Column(
            "currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
            name=op.f("fk_TelegramContext_user_id_User"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_TelegramContext")),
    )
    op.create_index(
        op.f("ix_TelegramContext_id"), "TelegramContext", ["id"], unique=True
    )
    op.create_table(
        "Wallet",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "balance_currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=False,
        ),
        sa.Column(
            "balance_amount", sa.DECIMAL(precision=19, scale=4), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_Wallet_user_id_User")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Wallet")),
    )
    op.create_index(
        op.f("ix_Wallet_user_id"), "Wallet", ["user_id"], unique=False
    )
    op.create_table(
        "Order",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "sub_total_amount",
            sa.NUMERIC(precision=19, scale=4),
            nullable=False,
        ),
        sa.Column(
            "sub_total_currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "AWAITING_PAYMENT",
                "CONFIRMED",
                "CANCELLED",
                "EXPIRED",
                "FAILED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum("WALLET", "PAYMENT", name="paymentsourcetype"),
            nullable=True,
        ),
        sa.Column("source_payment_id", sa.UUID(), nullable=True),
        sa.Column(
            "position",
            PositionSnapshotType(astext_type=Text()),
            nullable=False,
        ),
        sa.Column(
            "items",
            sa.ARRAY(ItemSnapshotType(astext_type=Text()), as_tuple=True),
            nullable=True,
        ),
        sa.Column("items_amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "awaited_payment_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_coupon_id", sa.UUID(), nullable=True),
        sa.Column(
            "discount_amount", sa.NUMERIC(precision=19, scale=4), nullable=True
        ),
        sa.Column(
            "discount_currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=True,
        ),
        sa.Column(
            "total_amount", sa.NUMERIC(precision=19, scale=4), nullable=False
        ),
        sa.Column(
            "total_currency",
            sa.Enum("USD", "RUB", "UAH", "KZT", name="currency"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["applied_coupon_id"],
            ["Coupon.id"],
            name=op.f("fk_Order_applied_coupon_id_Coupon"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["User.id"],
            name=op.f("fk_Order_customer_id_User"),
        ),
        sa.ForeignKeyConstraint(
            ["source_payment_id"],
            ["Payment.id"],
            name=op.f("fk_Order_source_payment_id_Payment"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Order")),
    )
    op.create_index(
        op.f("ix_Order_customer_id"), "Order", ["customer_id"], unique=False
    )
    op.create_table(
        "Position",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column(
            "name", LocalizedTextType(astext_type=Text()), nullable=False
        ),
        sa.Column(
            "description", LocalizedTextType(astext_type=Text()), nullable=True
        ),
        sa.Column(
            "media", sa.ARRAY(FileKeyType(astext_type=Text())), nullable=False
        ),
        sa.Column(
            "warehouse",
            WarehouseStrategyType(astext_type=Text()),
            nullable=False,
        ),
        sa.Column(
            "price", PositionPriceType(astext_type=Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "ARCHIVED", name="positionstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["Category.id"],
            name=op.f("fk_Position_category_id_Category"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["User.id"],
            name=op.f("fk_Position_creator_id_User"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Position")),
    )
    op.create_index(
        "uq_Position_name_values_en",
        "Position",
        [sa.literal_column("(name->'values'->>'en')")],
        unique=True,
        postgresql_where=sa.text("(name->'values'->>'en') IS NOT NULL"),
    )
    op.create_index(
        "uq_Position_name_values_ru",
        "Position",
        [sa.literal_column("(name->'values'->>'ru')")],
        unique=True,
        postgresql_where=sa.text("(name->'values'->>'ru') IS NOT NULL"),
    )
    op.create_table(
        "CouponRedemption",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("coupon_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RESERVED",
                "CONFIRMED",
                "CANCELLED",
                name="couponredemptionstatus",
            ),
            nullable=False,
        ),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["Coupon.id"],
            name=op.f("fk_CouponRedemption_coupon_id_Coupon"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["Order.id"],
            name=op.f("fk_CouponRedemption_order_id_Order"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
            name=op.f("fk_CouponRedemption_user_id_User"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_CouponRedemption")),
    )
    op.create_index(
        "uq_coupon_user_not_cancelled",
        "CouponRedemption",
        ["coupon_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status != 'CANCELLED'"),
    )
    op.create_table(
        "Item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column(
            "content", ItemContentType(astext_type=Text()), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE", "RESERVED", "SOLD", "ARCHIVED", name="itemstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("FINITE", "INFINITE", name="itemtype"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["User.id"], name=op.f("fk_Item_creator_id_User")
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["Position.id"],
            name=op.f("fk_Item_position_id_Position"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Item")),
    )
    op.create_index(
        op.f("ix_Item_position_id"), "Item", ["position_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Item_position_id"), table_name="Item")
    op.drop_table("Item")
    op.drop_index(
        "uq_coupon_user_not_cancelled",
        table_name="CouponRedemption",
        postgresql_where=sa.text("status != 'CANCELLED'"),
    )
    op.drop_table("CouponRedemption")
    op.drop_index(
        "uq_Position_name_values_ru",
        table_name="Position",
        postgresql_where=sa.text("(name->'values'->>'ru') IS NOT NULL"),
    )
    op.drop_index(
        "uq_Position_name_values_en",
        table_name="Position",
        postgresql_where=sa.text("(name->'values'->>'en') IS NOT NULL"),
    )
    op.drop_table("Position")
    op.drop_index(op.f("ix_Order_customer_id"), table_name="Order")
    op.drop_table("Order")
    op.drop_index(op.f("ix_Wallet_user_id"), table_name="Wallet")
    op.drop_table("Wallet")
    op.drop_index(op.f("ix_TelegramContext_id"), table_name="TelegramContext")
    op.drop_table("TelegramContext")
    op.drop_table("ReferrerProfile")
    op.drop_index(
        op.f("ix_ReferralAward_referrer_id"), table_name="ReferralAward"
    )
    op.drop_table("ReferralAward")
    op.drop_table("Payment")
    op.drop_table("Coupon")
    op.drop_index(
        "uq_Category_name_values_ru",
        table_name="Category",
        postgresql_where=sa.text("(name->'values'->>'ru') IS NOT NULL"),
    )
    op.drop_index(
        "uq_Category_name_values_en",
        table_name="Category",
        postgresql_where=sa.text("(name->'values'->>'en') IS NOT NULL"),
    )
    op.drop_table("Category")
    op.drop_table("User")
    op.drop_table("ReferralPolicy")
    op.drop_table("PaymentCommissionRule")
    # ### end Alembic commands ###
