from main.ioc.app import (
    CategoryHandlersProvider,
    CouponHandlersProvider,
    OrderHandlersProvider,
    PaymentHandlersProvider,
    PositionHandlersProvider,
    ReferralHandlersProvider,
    ReportHandlersProvider,
    UserHandlersProvider,
    WalletHandlersProvider,
)
from main.ioc.config import ConfigurationProvider
from main.ioc.domain import DomainServicesProvider
from main.ioc.infra import (
    AiogramProvider,
    BotSettingsAdaptersProvider,
    CategoryAdaptersProvider,
    CommonAdaptersProvider,
    CouponAdaptersProvider,
    CryptoBotProvider,
    GoogleTranslatorProvider,
    OrderAdaptersProvider,
    PaymentAdaptersProvider,
    PositionAdaptersProvider,
    RedisProvider,
    ReferralAdaptersProvider,
    ReportAdaptersProvider,
    RetortProvider,
    SqlAlchemyProvider,
    TaskIqProvider,
    TelegramAuthenticationAdaptersProvider,
    UserAdaptersProvider,
    WalletAdaptersProvider,
)
from main.ioc.presentation import AiogramAdaptersProvider

from .providers import PROVIDERS

__all__ = (
    "PROVIDERS",
    "AiogramAdaptersProvider",
    "AiogramProvider",
    "BotSettingsAdaptersProvider",
    "CategoryAdaptersProvider",
    "CategoryHandlersProvider",
    "CommonAdaptersProvider",
    "ConfigurationProvider",
    "CouponAdaptersProvider",
    "CouponHandlersProvider",
    "CryptoBotProvider",
    "DomainServicesProvider",
    "GoogleTranslatorProvider",
    "OrderAdaptersProvider",
    "OrderHandlersProvider",
    "PaymentAdaptersProvider",
    "PaymentHandlersProvider",
    "PositionAdaptersProvider",
    "PositionHandlersProvider",
    "RedisProvider",
    "ReferralAdaptersProvider",
    "ReferralHandlersProvider",
    "ReportAdaptersProvider",
    "ReportHandlersProvider",
    "RetortProvider",
    "SqlAlchemyProvider",
    "TaskIqProvider",
    "TelegramAuthenticationAdaptersProvider",
    "UserAdaptersProvider",
    "UserHandlersProvider",
    "WalletAdaptersProvider",
    "WalletHandlersProvider",
)
