from dishka import Provider
from main.ioc.app import (
    CategoryHandlersProvider,
    CouponHandlersProvider,
    OrderHandlersProvider,
    PaymentHandlersProvider,
    PositionHandlersProvider,
    ReferralHandlersProvider,
    ReportHandlersProvider,
    UserHandlersProvider,
    WalletHandlersProvider,
)
from main.ioc.config import ConfigurationProvider
from main.ioc.domain import DomainServicesProvider
from main.ioc.infra import (
    AiogramProvider,
    BotSettingsAdaptersProvider,
    CategoryAdaptersProvider,
    CommonAdaptersProvider,
    CouponAdaptersProvider,
    CryptoBotProvider,
    GoogleTranslatorProvider,
    OrderAdaptersProvider,
    PaymentAdaptersProvider,
    PositionAdaptersProvider,
    RedisProvider,
    ReferralAdaptersProvider,
    ReportAdaptersProvider,
    RetortProvider,
    SqlAlchemyProvider,
    TaskIqProvider,
    TelegramAuthenticationAdaptersProvider,
    UserAdaptersProvider,
    WalletAdaptersProvider,
)
from main.ioc.presentation import AiogramAdaptersProvider

PROVIDERS: tuple[Provider, ...] = (
    UserHandlersProvider(),
    ConfigurationProvider(),
    DomainServicesProvider(),
    UserAdaptersProvider(),
    RetortProvider(),
    CommonAdaptersProvider(),
    AiogramProvider(),
    SqlAlchemyProvider(),
    RedisProvider(),
    TelegramAuthenticationAdaptersProvider(),
    CategoryHandlersProvider(),
    CategoryAdaptersProvider(),
    BotSettingsAdaptersProvider(),
    GoogleTranslatorProvider(),
    AiogramAdaptersProvider(),
    PaymentHandlersProvider(),
    PaymentAdaptersProvider(),
    CryptoBotProvider(),
    TaskIqProvider(),
    WalletAdaptersProvider(),
    WalletHandlersProvider(),
    PositionAdaptersProvider(),
    PositionHandlersProvider(),
    CouponHandlersProvider(),
    CouponAdaptersProvider(),
    OrderAdaptersProvider(),
    ReferralHandlersProvider(),
    ReferralAdaptersProvider(),
    OrderHandlersProvider(),
    ReportHandlersProvider(),
    ReportAdaptersProvider(),
)
