from domain.common.exception import DomainError


class CouponError(DomainError): ...


class CouponPermissionDenied(CouponError): ...


class CouponAlreadyExists(CouponError): ...


class CouponAlreadyUsedByUser(CouponError): ...


class CouponRevoked(CouponError): ...


class CouponAlreadyRevoked(CouponError): ...


class CouponNotStarted(CouponError): ...


class CouponExpired(CouponError): ...


class CouponDiscountUnsupportedCurrency(CouponError): ...
