class DomainError(Exception): ...


class DomainPermissionDeniedError(DomainError): ...


class EntityNotFoundError(DomainError): ...


class DomainConflictError(DomainError): ...


class DomainRuleViolationError(DomainError): ...


class ValueObjectError(DomainError): ...
