class AppError(Exception): ...


class BootstrapError(AppError): ...


class AppInfrastructureError(AppError): ...


class AppExternalServiceError(AppError): ...


class DataCorruptionError(AppError): ...
