from app.product.position.cmd import (
    AddPositionItem,
    AddPositionItems,
    AddPositionMedia,
    ArchiveAllPositionItems,
    ArchiveAllPositionsInCategory,
    ArchivePosition,
    ArchivePositionItem,
    ChangePositionDescriptionDefaultLang,
    ChangePositionNameDefaultLang,
    ChangePositionPriceBaseCurrency,
    ConvertPositionPriceToOthers,
    CreatePosition,
    DeleteAllPositionItems,
    DeleteAllPositionsInCategory,
    DeletePosition,
    DeletePositionItem,
    RecoverPosition,
    RecoverPositionItem,
    RemovePositionDescription,
    RemovePositionMedia,
    RemovePositionName,
    ReplacePositionItem,
    ReplacePositionMedia,
    SetPositionDescription,
    SetPositionName,
    SetPositionPrice,
    TranslatePositionDescriptionToOthers,
    TranslatePositionNameToOthers,
)
from app.product.position.query import (
    GetPosition,
    GetPositionItem,
    GetPositionWithItemsAmount,
    ListPositionItems,
    ListPositionsByCategory,
    ListPositionsShortByCategory,
    ListPositionsWithItemsAmountByCategory,
)
from dishka import Provider, Scope, provide_all


class PositionHandlersProvider(Provider):
    scope = Scope.REQUEST

    commands = provide_all(
        CreatePosition,
        AddPositionItems,
        ChangePositionDescriptionDefaultLang,
        AddPositionMedia,
        ChangePositionNameDefaultLang,
        RecoverPosition,
        ArchivePosition,
        RemovePositionDescription,
        RemovePositionMedia,
        RemovePositionName,
        ReplacePositionMedia,
        SetPositionDescription,
        SetPositionName,
        SetPositionPrice,
        TranslatePositionNameToOthers,
        TranslatePositionDescriptionToOthers,
        ConvertPositionPriceToOthers,
        ReplacePositionItem,
        AddPositionItem,
        ArchivePositionItem,
        ChangePositionPriceBaseCurrency,
        DeletePosition,
        DeletePositionItem,
        DeleteAllPositionsInCategory,
        DeleteAllPositionItems,
        ArchiveAllPositionsInCategory,
        RecoverPositionItem,
        ArchiveAllPositionItems,
    )

    queries = provide_all(
        ListPositionsByCategory,
        GetPosition,
        GetPositionWithItemsAmount,
        ListPositionsShortByCategory,
        ListPositionItems,
        GetPositionItem,
        ListPositionsWithItemsAmountByCategory,
    )
