from domain.common.exception import DomainError


class OrderError(DomainError): ...


class OrderCouponApplicationForbidden(OrderError): ...


class OrderCancellationForbidden(OrderError): ...


class OrderPermissionDenied(OrderError): ...


class OrderFailureForbidden(OrderError): ...


class OrderExpirationForbidden(OrderError): ...


class OrderConfirmationForbidden(OrderError): ...


class OrderAwaitingPaymentForbidden(OrderError): ...


class OrderCurrencyChangeForbidden(OrderError): ...


class OrderItemsAmountChangeForbidden(OrderError): ...


class OrderFreePaymentForbidden(OrderError): ...


class OrderPaymentRequired(OrderError): ...
