from domain.common.exception import DomainError


class PaymentError(DomainError): ...


class PaymentPermissionDenied(PaymentError): ...


class PaymentStartForbidden(PaymentError): ...


class PaymentCheckForbidden(PaymentError): ...


class PaymentCancellationForbidden(PaymentError): ...


class PaymentConfirmationForbidden(PaymentError): ...


class PaymentFailureForbidden(PaymentError): ...
